// <auto-generated />
namespace Dist_Lab2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class messageREp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(messageREp));
        
        string IMigrationMetadata.Id
        {
            get { return "201510081753371_messageREp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
